name: picturebook
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # shared_preferences: ^2.2.2
  shared_preferences: ^2.5.2

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.20.0
  path_provider: ^2.1.5
  video_player: ^2.9.5
  flutter_dotenv: ^5.2.1
  pdfx: 
    git:
      url: 'https://github.com/ScerIO/packages.flutter' 
      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'  
      path: packages/pdfx
  flutter_cached_pdfview: ^0.4.3

  # syncfusion_flutter_pdfviewer: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/splashvideo.mp4
    - assets/images/bookpage.jpg
    - assets/images/background.jpg
    - assets/images/read_button.png
    - assets/images/listen_button.png
    - assets/images/record_button.png
    - assets/images/recording_button.png
    - assets/images/home_button_green.png
    - assets/images/home_button_blue.png
    - assets/images/previous_button.png
    - assets/images/next_button.png
    - assets/images/button_box.png
    - assets/images/volume_lable.png
    - assets/images/play_button.png
    - .env.dev
    - .env.prod
    - assets/books/pdf.pdf